Squashed commit of the following:
commit d5ab44f4ceeb164d114b181f7d74f95bafd44ff1
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Wed Aug 23 09:04:50 2023 -0400

    Bump version: 1.4.71 → 1.4.72

commit a918ca18549e3d4616c403e4aa8787bc0ca023eb
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Wed Aug 23 09:04:33 2023 -0400

    None of the above and all of the above elements now have an id and value set to True; fix issue with field lookup not working right after clicking back button; enable pseudo fields varname[nota] and varname[aota] to be used with showif

commit 88a8b4201ff1ed2392559ac7533cf446c71df21b
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Tue Aug 22 19:15:21 2023 -0400

    Bump version: 1.4.70 → 1.4.71

commit 9210b4740ba2f8b5275b03fc5a4e26d7d8f47636
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Tue Aug 22 19:14:53 2023 -0400

    adapted val and getField so that the None of above and All of the above checkboxes can be accessed and controlled; fixed error with GitHub URLs; stricter controls on variable names in YAML

commit 30c1e1dd17f4635fb9650c22b7dd222e6e5dfecc
Merge: a818bd0e8 c0f1feda5
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Tue Aug 22 14:25:20 2023 -0400

    Merge branch 'master' of github.com:jhpyle/docassemble

commit a818bd0e8ff0f7e20174e5f01c8ada2a8bf0f92e
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Tue Aug 22 14:24:10 2023 -0400

    none of the above and all of the above should trigger a change event when clicked

commit c0f1feda5ab016d3f8feefa9d7f9e6cb7b3c0070
Author: Bryce Willey <Bryce.Steven.Willey@gmail.com>
Date:   Tue Aug 22 11:41:13 2023 -0400

    Allow the get_branches() js to work with `#egg`

    Removes the `#egg` from the end of GitHub URLs if present, so we can still
    get a list of github branches; they don't appear otherwise.

commit 97ad1168c97c0a5f01bc43665d9497358d20041c
Author: Bryce Willey <Bryce.Steven.Willey@gmail.com>
Date:   Tue Aug 22 11:18:45 2023 -0400

    Quick fix for wrong variable name and pip issues

    github_url -> giturl

    pip also complains if we don't strip off the `#egg` from the given URL,
    linking to https://github.com/pypa/pip/pull/11617.

commit 09723e06ef26b49a38c00370495c743b9be4619e
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Aug 20 21:47:17 2023 -0400

    Bump version: 1.4.69 → 1.4.70

commit 4d5c644da6c0d0ba07249655f87fdbf1c47b18cc
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Aug 20 09:20:59 2023 -0400

    support for GitHub URLs that specify a package name with egg=; fix to js show if bug; adjustments to terms/auto terms so that terms are highlighted appropriately even if the same term is specified in multiple places; fix to locale setting code; speed improvements for checking if admin user needs to change password; improved nascent web server reload capability; supervisorctl altered so that initialize, postgres, and redis stop simultaneously

commit 0f66978c91a13f5ca141dcc821fa4c698056602c
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Tue Aug 15 21:33:43 2023 -0400

    Bump version: 1.4.68 → 1.4.69

commit bb259cc4acbb29f632efc6562b258e1dd13025c8
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Tue Aug 15 21:33:03 2023 -0400

    combobox aria-label translation; fix to Markdown-to-HTML conversion in popover help

commit ca0b2ff5af88ad358283aa3505a75f3512a8e2b6
Merge: 76d29f744 2e91483f5
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Tue Aug 15 08:11:34 2023 -0400

    Merge branch 'master' of github.com:jhpyle/docassemble

commit 2e91483f5f32f6797f549ddc14b8ca117cb693b3
Author: Bryce Willey <Bryce.Steven.Willey@gmail.com>
Date:   Mon Aug 14 09:41:50 2023 -0400

    Added a label for the combobox button

    aXe notes that the combobox dropdown button should have a label. This didn't
    show up during screen reader testing because it's not in the tab order.
    However, it should still be present, as there are other ways of having the
    screen read to you.

commit 76d29f744725a43ec2eb22d2a6754389b378bf01
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Thu Aug 10 20:15:56 2023 -0400

    fixed the response of val() for datatype object and datatype object_radio

commit f643fde71bc9bd4e8985ee241063008c4e50c32b
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Thu Aug 10 09:39:16 2023 -0400

    Bump version: 1.4.67 → 1.4.68

commit d5058c1cbc2ade67300a5750f653863c99870335
Merge: 72b82854e 5f37652fd
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Aug 6 11:58:25 2023 -0400

    Merge branch 'master' of github.com:jhpyle/docassemble

commit 72b82854e7647afe53efdf320b3850ac80162c80
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Aug 6 11:57:56 2023 -0400

    fixed locale functionality; fixed issue with non-required object fields raising exception instead of setting to None; fix to LDAP fallback credential checking

commit 5f37652fd45d68ecf5074b12f76bb5ed0510db09
Author: neven <neven@luetic.de>
Date:   Fri Aug 4 17:00:03 2023 +0200

    ldap: added support for ldap over TLS, added support for bind, anonymous bind

commit a108176fb3ca7ad7b79d31e0f7dc0d7d377d10d7
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Wed Aug 2 02:25:19 2023 +0000

    Bump cryptography from 41.0.2 to 41.0.3 in /docassemble_webapp

    Bumps [cryptography](https://github.com/pyca/cryptography) from 41.0.2 to 41.0.3.
    - [Changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst)
    - [Commits](https://github.com/pyca/cryptography/compare/41.0.2...41.0.3)

    ---
    updated-dependencies:
    - dependency-name: cryptography
      dependency-type: direct:production
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

commit c6e516496998625c6ca038ec393afdfa758a7d92
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Fri Jul 28 21:58:02 2023 -0400

    Bump version: 1.4.66 → 1.4.67

commit 405fea19dc4baa20da5df6efbffff828aadb06b9
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Fri Jul 28 21:57:57 2023 -0400

    upgraded webdriver_manager; adapted the delete method of DAGlobal so that it can be called repeatedly without error

commit e84c0c923b40d5a474e2d535f8a5e72d7607d5f4
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Mon Jul 24 08:39:50 2023 -0400

    Bump version: 1.4.65 → 1.4.66

commit dd630a1b98d2802733b280356bf16b0787c02366
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Jul 23 11:27:56 2023 -0400

    update python dependencies; adjust for new versions of matplotlib, selenium, and markdown

commit cff82a6d7e85eaba706f6d53df410be52c8c3fb1
Merge: c0fa076b5 78d886d24
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sat Jul 22 13:04:54 2023 -0400

    Merge branch 'master' of github.com:jhpyle/docassemble

commit c0fa076b53eb17095893a8eba45b4cb18b1b3d72
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sat Jul 22 13:04:43 2023 -0400

    avoid error with os.makedirs where directory exists even though os.path.isdir() evaluates to false immediately before os.makedirs is called; avoid creating directory for Playground user who does not exist

commit 78d886d246e60b05c90c254010d9d384042e98ec
Merge: d79fcfef7 6ed3ccda1
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sat Jul 22 13:02:24 2023 -0400

    Merge pull request #665 from jhpyle/dependabot/pip/docassemble_webapp/cryptography-41.0.2

    Bump cryptography from 39.0.1 to 41.0.2 in /docassemble_webapp

commit d79fcfef7f0383065c6f3f8c1d8f1d62fff72f01
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Thu Jul 20 12:10:38 2023 +0000

    Bump pygments from 2.14.0 to 2.15.0 in /docassemble_webapp

    Bumps [pygments](https://github.com/pygments/pygments) from 2.14.0 to 2.15.0.
    - [Release notes](https://github.com/pygments/pygments/releases)
    - [Changelog](https://github.com/pygments/pygments/blob/master/CHANGES)
    - [Commits](https://github.com/pygments/pygments/compare/2.14.0...2.15.0)

    ---
    updated-dependencies:
    - dependency-name: pygments
      dependency-type: direct:production
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

commit b32d746c477623d134d750f11f614f71cb544ca8
Author: Bryce Willey <Bryce.Steven.Willey@gmail.com>
Date:   Wed Jul 19 16:56:08 2023 -0400

    JSON-ize things returned from a background action

    This continues on work in https://github.com/jhpyle/docassemble/commit/8d1b84777ce626170e44d83e09de523bbfca5e50#diff-4c8bf136c393acf44c18098d2b935b3a005636e57574530acffdf552432360faR5751 (1.4.0). That commit ran avoided running the results from a refresh from a background action, but only if `do_action` was set. There is also a section that get the final values from finished workers directly that hadn't been calling `safe_json` on the results, causing errors like:

    ```
      File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 6250, in checkin
        return jsonify_with_cache(success=True, chat_status=chatstatus, num_peers=num_peers, help_available=help_available, phone=call_forwarding_message, observerControl=observer_control, commands=commands, checkin_code=checkin_code)
      File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/docassemble/webapp/server.py", line 5970, in jsonify_with_cache
        response = jsonify(*pargs, **kwargs)
      ...
      File "/usr/share/docassemble/local3.10/lib/python3.10/site-packages/flask/json/provider.py", line 120, in _default
        raise TypeError(f"Object of type {type(o).__name__} is not JSON serializable")
    TypeError: Object of type DAList is not JSON serializable
    ```

    This PR simply calls `safe_json` on those values, so there aren't extra errors that get logged, even if no user-visible errors happen from the behavior (since refresh isn't doing anything with the checkin json).

commit 6ed3ccda1056f58c2321c4735665442f68c68c4a
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Sat Jul 15 00:57:54 2023 +0000

    Bump cryptography from 39.0.1 to 41.0.2 in /docassemble_webapp

    Bumps [cryptography](https://github.com/pyca/cryptography) from 39.0.1 to 41.0.2.
    - [Changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst)
    - [Commits](https://github.com/pyca/cryptography/compare/39.0.1...41.0.2)

    ---
    updated-dependencies:
    - dependency-name: cryptography
      dependency-type: direct:production
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

commit cb37dc1eaf096bd32b03f60265428fcdb8b21175
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Thu Jul 13 21:12:47 2023 -0400

    Bump version: 1.4.64 → 1.4.65

commit 7788c0e0524c119f62a689d1fbee557b12999ffe
Merge: ba1af8e22 b4d40e50b
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Thu Jul 13 19:54:58 2023 -0400

    Merge pull request #664 from jhpyle/dependabot/pip/docassemble_webapp/grpcio-1.53.0

    Bump grpcio from 1.51.1 to 1.53.0 in /docassemble_webapp

commit ba1af8e22981a2739f17e07bd5fb1d3a31e482df
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Tue Jul 11 13:47:22 2023 -0400

    Bump version: 1.4.63 → 1.4.64

commit b4d40e50b16f970d3c22adc21f4320d84eb9b5e1
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Wed Jul 5 21:45:35 2023 +0000

    Bump grpcio from 1.51.1 to 1.53.0 in /docassemble_webapp

    Bumps [grpcio](https://github.com/grpc/grpc) from 1.51.1 to 1.53.0.
    - [Release notes](https://github.com/grpc/grpc/releases)
    - [Changelog](https://github.com/grpc/grpc/blob/master/doc/grpc_release_schedule.md)
    - [Commits](https://github.com/grpc/grpc/compare/v1.51.1...v1.53.0)

    ---
    updated-dependencies:
    - dependency-name: grpcio
      dependency-type: direct:production
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

commit 1f87cc184c6b2a9f15f4bb844891ea3b0dcba6f4
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Jul 2 11:47:34 2023 -0400

    Bump version: 1.4.62 → 1.4.63

commit ef78c24115a47c8ff2a3d238d4ce9782a0d91b0a
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Wed Jun 21 21:35:31 2023 -0400

    Bump version: 1.4.61 → 1.4.62

commit c5cea122b74895b5a4dc3901c3c22605d3b62972
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Wed Jun 21 21:35:25 2023 -0400

    administrative interviews error in menu; checkbox fields subject to show if not able to be located; object_checkboxes false values not being processed

commit a8827f98e7f3bfb2b8806711962a4639221e9bab
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Jun 18 07:10:05 2023 -0400

    Bump version: 1.4.60 → 1.4.61

commit 96406778dfd14e2fec9bc11b7a30b656b43e3da5
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Jun 18 07:09:58 2023 -0400

    added test for raw datatype; adjusted change event triggers on combobox for better compatibility with the 'show if' system

commit 8021adb51c61e4e17f5c155ffa091264a307070a
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sat Jun 17 08:40:42 2023 -0400

    Bump version: 1.4.59 → 1.4.60

commit 4eb6976a898f67528b98f5fa6cebba2a1e3cb758
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sat Jun 17 08:40:37 2023 -0400

    added support for PostgreSQL 15; fixed issue with datatype: raw

commit ddfa52a042851022d1d5b315c5dac03767fad9f7
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Mon Jun 12 11:51:07 2023 -0400

    Bump version: 1.4.58 → 1.4.59

commit c62b9ae3b3e4ced6b73b832ef7ba3923dafcf378
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sat Jun 10 16:19:44 2023 -0400

    Bump version: 1.4.57 → 1.4.58

commit 9781ad8ed75fa4c5d696e7d4b3bd6cc335ef2726
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sat Jun 10 16:19:36 2023 -0400

    keyword argument evaluate for force_ask(), force_gather(), and reconsider(); fixed value() so that the exceptions it raises correspond with what would be raised if the expression were evaluated; fixed the as_data method of Question so that code-generated fields show up as actual fields; adapted CSS of the signature question so that it only goes into compact mode in landscape mode; removed the back button from compact mode when question back button is enabled; updated the color of the navigation bar in compact mode; fixed error with the rtf to docx file type; fixed error with defining instanceName of an attachment; removed obsolete code from basic-questions.yml; fixed the reconsider modifier so that iterator variables are interpolated

commit fe4fce5a500f8387e5a98128423b5b58b78c891d
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Mon Jun 5 19:13:52 2023 -0400

    Bump version: 1.4.56 → 1.4.57

commit 87373efb399e66347b5b8978e8f7631266ada2e9
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Jun 4 15:35:58 2023 -0400

    Bump version: 1.4.55 → 1.4.56

commit 8f105527a964ae8e396cd286005bb0b548d010ff
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Jun 4 15:34:10 2023 -0400

    not upgrading cryptography because other dependencies are not ready for it

commit e4f983e10201a1ab149d36799009494b8d8177b6
Merge: 625677028 9810a2cb1
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Jun 4 09:35:42 2023 -0400

    Merge branch 'master' of github.com:jhpyle/docassemble

commit 625677028c5e71caa69e8db923c2b2170e566715
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun Jun 4 09:33:17 2023 -0400

    force_ask, reconsider, and related features now attempt to compute the instance names of objects before raising undefined variable exceptions; the JavaScript functions getField, setField, and val can be used with multiple choice fields; the hide corner interface feature; custom URLs in administrative interviews; additional functions available as Jinja2 filters

commit 9810a2cb1783f8c582fd2229a570ba5fcb38eb32
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Fri Jun 2 20:18:10 2023 +0000

    Bump cryptography from 39.0.1 to 41.0.0 in /docassemble_webapp

    Bumps [cryptography](https://github.com/pyca/cryptography) from 39.0.1 to 41.0.0.
    - [Changelog](https://github.com/pyca/cryptography/blob/main/CHANGELOG.rst)
    - [Commits](https://github.com/pyca/cryptography/compare/39.0.1...41.0.0)

    ---
    updated-dependencies:
    - dependency-name: cryptography
      dependency-type: direct:production
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

commit af6d93585a864c738ac1690946c529afb97f95f1
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue May 23 06:08:43 2023 +0000

    Bump requests from 2.28.2 to 2.31.0 in /docassemble_webapp

    Bumps [requests](https://github.com/psf/requests) from 2.28.2 to 2.31.0.
    - [Release notes](https://github.com/psf/requests/releases)
    - [Changelog](https://github.com/psf/requests/blob/main/HISTORY.md)
    - [Commits](https://github.com/psf/requests/compare/v2.28.2...v2.31.0)

    ---
    updated-dependencies:
    - dependency-name: requests
      dependency-type: direct:production
    ...

    Signed-off-by: dependabot[bot] <support@github.com>

commit cc12b6a8d21594f133349b50b988c74b7b944955
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun May 21 18:01:10 2023 -0400

    Bump version: 1.4.54 → 1.4.55

commit 8a0db751cb5191efbedc5e0f5dbf0f40151ddaca
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun May 21 18:01:07 2023 -0400

    fixed issue with Run button in Playground sidebar

commit 97fd1ed36b1fdda50eae41e6cb071f4daebaf1eb
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun May 21 15:17:09 2023 -0400

    Bump version: 1.4.53 → 1.4.54

commit 9ba99d1e1419f82197b7af808279f37a74772584
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun May 21 15:15:57 2023 -0400

    corrected setup.py to specify that Python 3.9 or greater is required

commit 9f31dd484f286966fc08d4b81656aad2f951e435
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sun May 21 12:16:33 2023 -0400

    Bump version: 1.4.52 → 1.4.53

commit 323fb7286a765e862c980d222a65e56eea319467
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Sat May 20 16:10:54 2023 -0400

    use importlib.resources instead of pkg_resources; add delete parameter to set_session_variables

commit 5cb2eec8c40920a0b97db8c63a184cfb8211d456
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Wed May 17 22:41:43 2023 -0400

    Bump version: 1.4.51 → 1.4.52

commit db596cb8a4c6c9975dc6aa555f2d9ebfc7039718
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Wed May 17 20:44:29 2023 -0400

    Upgraded Flask; adapted keycloak API calls

commit 87d212cfa8214b7223aa6b77c572f370249d8f1f
Merge: 3c64758af b67d9f6c3
Author: Jonathan Pyle <jhpyle@gmail.com>
Date:   Thu May 11 20:44:37 2023 -0400

    Merge pull request #644 from jhpyle/dependabot/pip/docassemble_webapp/flask-2.3.2

    Bump flask from 2.2.2 to 2.3.2 in /docassemble_webapp

commit b67d9f6c3894aecb8dd3efbd65810e112e1ab65d
Author: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Date:   Tue May 2 00:18:54 2023 +0000

    Bump flask from 2.2.2 to 2.3.2 in /docassemble_webapp

    Bumps [flask](https://github.com/pallets/flask) from 2.2.2 to 2.3.2.
    - [Release notes](https://github.com/pallets/flask/releases)
    - [Changelog](https://github.com/pallets/flask/blob/main/CHANGES.rst)
    - [Commits](https://github.com/pallets/flask/compare/2.2.2...2.3.2)

    ---
    updated-dependencies:
    - dependency-name: flask
      dependency-type: direct:production
    ...

    Signed-off-by: dependabot[bot] <support@github.com>